### Importação das bibliotecas

In [1]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Análise de Dados

In [2]:
df_order_reviews = pd.read_csv(f"{os.getcwd()}\\documentos\\olist_order_reviews_dataset.csv")

df_order_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.8 MB

O dataset apresenta dados nulos no título e nos comentários, porém nas notas da review se mantém ativas

In [3]:
colunas = ['review_score', 'review_comment_title', 'review_comment_message']

for col in colunas:
    print(f'{col}: {pd.unique(df_order_reviews[col])}\n')

review_score: [4 5 1 3 2]

review_comment_title: <ArrowStringArray>
[                        nan,                 'recomendo',
           'Super recomendo',   'Não chegou meu produto ',
                     'Ótimo',                'Muito bom.',
                       'Bom',              'Maravilhoso!',
          'Entrega perfeita',                  'MT lindo',
 ...
 'Não posso recomendar aind',      'Rápido porém não bom',
           'entregue rapido',                        '7 ',
      'Entrega super Rápida',              'Nota máxima!',
        'muito bom produto ', 'Não foi entregue o pedido',
           'OTIMA EMBALAGEM',            'Foto enganosa ']
Length: 4528, dtype: str

review_comment_message: <ArrowStringArray>
[                                                                                                                                                                                                    nan,
                                                                                                                                                                 'Recebi bem antes do prazo estipulado.',
                                                                                                  'Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa',
                        'aparelho eficiente. no site a marca do aparelho esta impresso como 3desinfector e ao chegar esta com outro nome...atualizar com a marca correta uma vez que é o mesmo aparelho',
                                                                                                                                                       'Mas um pouco ,travando...pelo valor ta Boa.\r\n',
                                                                                                                                              'Vendedor confiável, produto ok e entrega antes do prazo.',
                                                                                                                        'GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E ESSA COMPRA AGORA ME DECPCIONOU',
                                                                                                                                                                                               'Péssimo',
                                                                                                                                                                                          'Loja nota 10',
                                                                                                                                                                 'obrigado pela atençao amim dispensada',
 ...
                                                                                               'Ficamos muito satisfeitos com o produto, atende às nossas necessidades com muita facilidade. Recomendo!',
                                                                                                                 'Bom dia \r\nDas 6 unidades compradas só recebi 4 unidades, estou aguardando as demais',
                                                                                                               'Foto muito diferente principalmente a graninha sintética muito rala...diferente da foto',
                                                                                                                                            'Produto original,prazo de entrega rápido.Super satisfeito.',
 'Tive um problema na entrega em que o correio colocou no site como entregue dia 19/02 mais nao tinha entregue tentei contato com lannister e a loja em questao e impossivel por fone nem resposta tive',
                                                                                                                                            'para este produto recebi de acordo com a compra realizada!',
                                                                                                           'Entregou dentro do prazo. O produto chegou em condições perfeitas. Estou muito satisfeita! ',
                                                                         'O produto não foi enviado com NF, não existe venda sem NF, com certeza fico no aguardo do envio da NF podendo ser por e-mail.',
                                                                                                                                   'Excelente mochila, entrega super rápida. Super recomendo essa loja!',
                                                                                                                 'meu produto chegou e ja tenho que devolver, pois está com defeito , não segurar carga']
Length: 36160, dtype: str

In [4]:
df_order_reviews['review_comment_title'] = df_order_reviews['review_comment_title'].str.strip()
df_order_reviews['review_comment_message'] = df_order_reviews['review_comment_message'].str.strip()

Avaliação das Reviews Nulas

In [5]:
df_filtrado = df_order_reviews[df_order_reviews['review_comment_message'].isna()][
    ['order_id', 'review_score', 'review_comment_title', 'review_comment_message']
]

df_filtrado.info()

<class 'pandas.DataFrame'>
Index: 58247 entries, 0 to 99222
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                58247 non-null  str
 1   review_score            58247 non-null  int64
 2   review_comment_title    1729 non-null   str
 3   review_comment_message  0 non-null      str
dtypes: int64(1), str(3)
memory usage: 4.0 MB

In [6]:
# Avaliação dos Títulos das mensagens
for c in ['review_score', 'review_comment_title']:
    print(f'{c}: {pd.unique(df_filtrado[c])}')

review_score: [4 5 1 3 2]
review_comment_title: <ArrowStringArray>
[                        nan,                     'Ótimo',
     'Não recebi o produto.', 'Entrega antes do previsto',
                 'Recomendo',                       'bom',
                         '5',                         '4',
            'Excelente Loja',                     'ótimo',
 ...
             'não recomendo',                 'Capa sofá',
                'Não chegou',                         '6',
                 'Recomento',                    'Top 10',
                     'Médio',                  'Ótimo!!!',
          'Super satisfeito',           'OTIMA EMBALAGEM']
Length: 647, dtype: str

In [7]:
display(df_filtrado)

,order_id,review_score,review_comment_title,review_comment_message
0,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN
1,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN
2,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN
5,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN
6,e48aa0d2dcec3a2e87348811bcfdf22b,5,NaN,NaN
...,...,...,...,...
99217,48f7ee67313eda32bfcf5b9c1dd9522d,5,NaN,NaN
99218,d699c734a0b1c8111f2272a3f36d398c,5,NaN,NaN
99219,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN
99220,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN
99222,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN

In [ ]:
df_filtrado[df_filtrado['review_comment_title'].isna()]

,order_id,review_score,review_comment_title,review_comment_message
0,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN
1,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN
2,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN
5,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN
6,e48aa0d2dcec3a2e87348811bcfdf22b,5,NaN,NaN
...,...,...,...,...
99217,48f7ee67313eda32bfcf5b9c1dd9522d,5,NaN,NaN
99218,d699c734a0b1c8111f2272a3f36d398c,5,NaN,NaN
99219,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN
99220,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN
99222,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN

In [ ]:
# Como o título nulo e as mensagens nulas nos casos filtrados poderia avaliar por meio da nota que não estão nulos

pd.unique(df_filtrado[df_filtrado['review_comment_title'].isna()]['review_score'])

array([4, 5, 1, 3, 2])